title: Midgrabens International
description: World events with data
url: "https://midgrabens.com"
baseurl: ""
remote_theme: raviriley/agency-jekyll-theme
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
author: Inkwell
author_url: https://midgrabens.com
